### ISSUE TITLE
".default.trackPage is not a function"

### ISSUE THREAD

**Issue by siulca** [AmazingDreams/vue-matomo#10]
I'm using it in a project created with Vue CLI 3. 

"vue": "^2.5.17",
"vue-matomo": "^0.1.11",
"vue-router": "^3.0.1",

Matomo seems to make router fail with the following error:

![screen shot 2018-10-11 at 22 36 25](https://user-images.githubusercontent.com/6707451/46835452-21322600-cda6-11e8-8500-90bb8cba3ddb.png)

**Comment by siulca** [comment]
ROuter appears to be calling trackPage() which does not exist in matomo's API. Should it not be [trackPageView()](https://developer.matomo.org/api-reference/tracking-javascript) ?

![screen shot 2018-10-11 at 22 58 13](https://user-images.githubusercontent.com/6707451/46836428-496f5400-cda9-11e8-8137-6963c79cf8c0.png)

**Comment by AmazingDreams** [comment]
`vue-matomo` is definitely calling `trackPageView` (https://github.com/AmazingDreams/vue-matomo/blob/master/src/index.js#L46)

What do you have at `src/main.js` line 47? The stacktrace suggests it's being called there.

**Comment by siulca** [comment]
Line 47 is the closing bracket of the Vue() instance. It fails to initialize so it's pointing at that line.

**Comment by AmazingDreams** [comment]
It is weird. Do you think you can create a minimal reproduction script?

**Comment by siulca** [comment]
The minimal reproduction script works. I'll have to go through a process of elimination in my project to figure out what's going on. Not sure it's worth the trouble.

(As an aside, there's a coma missing in your instructions:)
![image](https://user-images.githubusercontent.com/6707451/46865606-08615900-ce16-11e8-9379-7ed1a0d2d560.png)

**Comment by AmazingDreams** [comment]
Ah right, that was fixed after the latest release. I'll make a new release for the documentation fix. I will close this one for now, just reopen when you've found anything related to vue-matomo.
