### ISSUE TITLE
rememberConsentGiven not working

### ISSUE THREAD

**Issue by devilwacause** [AmazingDreams/vue-matomo#103]
![image](https://user-images.githubusercontent.com/24920886/152613035-6b9edd9d-c07e-42a8-84a4-f75ba0f7efca.png)

I call that upon the user clicking "I consent" on a modal.  It never works.  However - clicking "I do not consent" DOES work with the following code 

![image](https://user-images.githubusercontent.com/24920886/152613123-9df2f797-7e90-4d3a-a4d9-ac893804084c.png)

**Comment by AmazingDreams** [comment]
I am not sure what you mean exactly with it is not working?
