### ISSUE TITLE
How to configure userId tracking?

### ISSUE THREAD

**Issue by badrul** [AmazingDreams/vue-matomo#113]
I have the following setup but unable correctly track userId. When user first visit, userId is undefined, after user log-in, matomo is still tracking userId as undefined unless I refresh vue page.

main.js
```
const app = createApp(App)
// matomo configuration
const matomoConfig = {
  ...
  userId: store.getters.user ? store.getters.user.user_id : undefined
}
app.use(VueMatomo, matomoConfig)
  .mount('#app')
```

**Comment by AmazingDreams** [comment]
I recommend doing:

```
this.$matomo.setUserId(newUserId)
this.$matomo.trackPageView()
// or
window._paq.push(['setUserId', newUserId])
window._paq.push(['trackPageView']);
```

As soon as your user id becomes available.

**Comment by atrujillofalcon** [comment]
> I recommend doing:
> 
> ```
> this.$matomo.setUserId(newUserId)
> this.$matomo.trackPageView()
> // or
> window._paq.push(['setUserId', newUserId])
> window._paq.push(['trackPageView']);
> ```
> 
> As soon as your user id becomes available.

But doesn't manually invoking trackPageView conflict with the router's automatic integration?
