### ISSUE TITLE
Cross Domain Linking

### ISSUE THREAD

**Issue by drilus** [AmazingDreams/vue-matomo#115]
Could you add 'enableCrossDomainLinking' to the Vue.use constructor?

Also, when using cross domain linking the setDomains parameter must be set:
_paq.push(["setDomains", ["*.domain1.com", "*.domain2.com"]]);

Is that the same as the domains parameter? If so, only CrossDomainLinking would need to be added.

**Comment by AmazingDreams** [comment]
You can use the `preInitActions`

```
Vue.use(VueMatomo, {
  ...
  preInitActions: [
    ['enableCrossDomainLinking']
  ],
})
```
