### ISSUE TITLE
TS Support

### ISSUE THREAD

**Issue by TheNaschkatze** [AmazingDreams/vue-matomo#116]
Hi, 

Is it in the pipeline to get typescript support?

**Comment by AmazingDreams** [comment]
No. Not only would I have to rewrite this project, I'd have to write TS interfaces for upstream code too.

**Comment by befresh-mweimerskirch** [comment]
For basic TypeScript support, you can add this to a file called vue-matomo.d.ts inside your projects that use vue-matomo:

```
declare module 'vue-matomo' {
    import {Plugin} from 'vue'
    const VueMatomo: Plugin
    export default VueMatomo
}
```
