### ISSUE TITLE
Outlinks not being tracked

### ISSUE THREAD

**Issue by siulca** [AmazingDreams/vue-matomo#12]
Since I started using vue-matomo the outlinks are no longer tracked as they were before. Is there a setting to enable this?

This is my setup:
```js
Vue.use(VueMatomo, {
  // Configure your matomo server and site
  host: '//website.com/piwik',
  siteId: 3,
  // Enables automatically registering pageviews on the router
  router: router,
  // Require consent before sending tracking information to matomo
  requireConsent: false,
  // Whether to track the initial page view
  trackInitialView: true,
  // Changes the default .js and .php endpoint's filename
  // Default: 'piwik'
  trackerFileName: 'piwik'
})```

**Comment by AmazingDreams** [comment]
I actually don't do much with outlinks. I didn't realize they were broken. I'll try to reproduce

**Comment by AmazingDreams** [comment]
Please check out v0.3.0 and let me know if it works

**Comment by siulca** [comment]
Outlinks tracking is now working on the latest version. Thank you for such swift action. Much appreciated.
