### ISSUE TITLE
Ignore some pages of router

### ISSUE THREAD

**Issue by nicolas-bonnel** [AmazingDreams/vue-matomo#14]
Hi,

Is it possible to ignore tracking of specific pages, including dynamic ones ?
For instance `/users/_id/edit`.

**Comment by AmazingDreams** [comment]
No, but it sounds like simple enough to implement. Do you reckon a boolean on a route object is enough? Something like this

```
{ 
    path: '/', 
    name: 'HelloWorld', 
    component: HelloWorld,
    meta: {
        analyticsIgnore: true
    }
}
```

**Comment by nicolas-bonnel** [comment]
I'm using nuxt, but I think I should manage to add meta information with a middleware. Your solution is ok for me.

**Comment by AmazingDreams** [comment]
Check out v0.6.0 ;)
