### ISSUE TITLE
Add config option to disallow console

### ISSUE THREAD

**Issue by valedaemon** [AmazingDreams/vue-matomo#15]
Thank you for the plugin! Could a config option be added to not output the console messages? We're getting a decent bit of noise in the console, and while that is desirable for a development environment, being able to not have that for production would be of a great benefit.

Thank you very much!

**Comment by AmazingDreams** [comment]
Merged, thanks!

**Comment by AmazingDreams** [comment]
v0.6.0 is available ;)
