### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by keikoro** [AmazingDreams/vue-matomo#18]
Hi there, I'm getting the following error even when trying the example code provided in the README:

```
ERROR in   Error: /PATH/TO/SCRIPT/matomo.js:11142
  !function(t,e){if(true)module.exports=e();else if("function"==typeof define&&define.amd)define([],e);else{var n=e();for(var i in n)("object"  ==typeof exports?exports:t)[i]=n[i]}}("undefined"!=typeof self?self:this,function(){return function(t){function e(i){if(n[i])return n[i].exp  orts;var r=n[i]={i:i,l:!1,exports:{}};return t[i].call(r.exports,r,r.exports,e),r.l=!0,r.exports}var n={};return e.m=t,e.c=n,e.d=function(t,  n,i){e.o(t,n)||Object.defineProperty(t,n,{configurable:!1,enumerable:!0,get:i})},e.n=function(t){var n=t&&t.__esModule?function(){return t.d  efault}:function(){return t};return e.d(n,"a",n),n},e.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},e.p="",e(e.s=0)}([fu  nction(t,e,n){"use strict";function i(t){var e=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},n=Object.assign({},a,e),i=n.host,r=  n.siteId,s=n.trackerFileName,u=o.a.getTracker(i+"/"+s+".php",r);t.prototype.$piwik=u,t.prototype.$matomo=u,n.requireConsent&&u.requ
  ReferenceError: window is not defined
  
  - matomo.js:11142 Object.<anonymous>
    /PATH/TO/SCRIPT/matomo.js:11142:1685
  
  - matomo.js:11142 Object.<anonymous>
    /PATH/TO/SCRIPT/matomo.js:11142:58057
  
  - matomo.js:11142 e
    /PATH/TO/SCRIPT/matomo.js:11142:331
  
  - matomo.js:11142 Object.<anonymous>
    /PATH/TO/SCRIPT/matomo.js:11142:1482
  
  - matomo.js:11142 e
    /PATH/TO/SCRIPT/matomo.js:11142:331
  
  - matomo.js:11142 
    /PATH/TO/SCRIPT/matomo.js:11142:688
  
  - matomo.js:11142 
    /PATH/TO/SCRIPT/matomo.js:11142:697
  
  - matomo.js:11142 96K9
    /PATH/TO/SCRIPT/matomo.js:11142:39
  
  - matomo.js:11142 Object.96K9
    /PATH/TO/SCRIPT/matomo.js:11142:178
  
  - matomo.js:21 __webpack_require__
    /PATH/TO/SCRIPT/matomo.js:21:30
  


  Build failed with errors.
```

"vue": "^2.5.2",
"vue-matomo": "^3.7.0-1",
"vue-router": "^3.0.1",

Also (unrelatedly): did that sudden version jump happen accidentally or...?

**Comment by keikoro** [comment]
It _could_ be I'm not... feeding the code into Vue correctly? I haven't really looked into plugins so far, but I'm using the example code in a file that's on the same hierarchical level as e.g. `material.js` (or indeed `main.js`).

**Comment by qdot** [comment]
I'm trying to integrate this into a vuepress document and I'm getting the same issue. Haven't quite tracked down why yet, just that it's something to do with the included matomo.js file from this library.

**Comment by AmazingDreams** [comment]
VuePress is like a static website compiler right? I guess the issue arises when it compiles in a non-browser environment.

Is there any way you can mark packages as 'client only' or whatever? So they won't be directly compiled?

Could you try to fork vue-matomo and edit the source, do something like `window = window || {}` before matomo is included and test with vuepress?

**Comment by qdot** [comment]
Yeah, I think this has something to do with webpack trying to injest the already minified and browser-only matomo.js file while trying to do static renders. Even if I can get window fixed up, then it starts complaining about other variables in that file.

Is there a reason vue-matomo is shipping/using the matomo.js file itself, versus using the matomo-tracker package? Just asking 'cause I've used that elsewhere without having this issue, but haven't really looked at motivations here.

**Comment by qdot** [comment]
Ok, did a bit more digging, here's the apparent solution for vuepress (haven't implemented myself yet, gonna try that now): 

https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

This may also fix the original bug issue, depending on how the rendering is happening?

**Comment by keikoro** [comment]
@qdot Thanks for the updates!

I ended up injecting the vanilla JS code into `index.html` using Webpack and a Webpack plugin because I eventually needed to separate it out/include it only conditionally (i.e. in production builds only), and the Matomo tracking data was also not to be committed to the project's repository.

I'd still be interested in making the plugin work, but I don't know if I can even (easily) use it the way the project demands.

**Comment by qdot** [comment]
I went ahead and wrote my own, and learned a good bit about SSR while I was at it. It's basically a combination of the ideas in your project (credited your repo in the README), and the normal matomo webtracker code:

https://github.com/qdot/vuepress-plugin-matomo

**Comment by AmazingDreams** [comment]
Good stuff, I actually used an include script in the first instance. Then people got confused because they couldn't use `this.$matomo` until the script finished loading. Then I went over to using a `Proxy` but I lost old browser support. And now I've just included the whole thing which causes non-browser based implementations to fail apparently.
