### ISSUE TITLE
Matomo integrations

### ISSUE THREAD

**Issue by Findus23** [AmazingDreams/vue-matomo#2]
Hi,

many thanks for your great plugin. I have now added it to the list of Matomo integrations:
https://matomo.org/integrate/#programming-language-platforms-and-frameworks

Would it maybe be possible to rename the plugin to Matomo (even though that would be a breaking change)?

When I find some time I'll try it out as I am currently tracking my vue app with a kind of hackish setup.

**Comment by AmazingDreams** [comment]
Sure. I'll get right at it. Thanks for adding the plugin to your website.

**Comment by AmazingDreams** [comment]
It's done. https://github.com/AmazingDreams/vue-matomo

**Comment by vesper8** [comment]
@Findus23 He changed the name the next day but your page is still linking to vue-piwik.. even though there is an automatic redirect
