### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by JiriChara** [AmazingDreams/vue-matomo#20]
Hi @AmazingDreams,

the latest changes from https://github.com/AmazingDreams/vue-matomo/pull/19 were unfortunately not published to npm, because the up-to-date dist folder was not included. :-)

Can you please re-deploy a new version?

**Comment by JiriChara** [comment]
Sorry - my mistake. It looks like the code is included in minified file

**Comment by AmazingDreams** [comment]
Sorry for not responding. I was a bit preoccupied. Glad you got it.
