### ISSUE TITLE
Reference Error in Production Build

### ISSUE THREAD

**Issue by bschulz87** [AmazingDreams/vue-matomo#24]
In dev mode everything works fine but when trying to load the app after building the page is white and console shows this error: `ReferenceError: assignment to undeclared variable JSON_PIWIK`

I use vue cli build project

```javascript
import Vue from 'vue'
import router from '@/router.js'
import VueMatomo from 'vue-matomo'

Vue.use(VueMatomo, {
  // Configure your matomo server and site by providing
  host: 'https://my.matomo.server',
  siteId: 1,

  // Changes the default .js and .php endpoint's filename
  // Default: 'piwik'
  trackerFileName: 'piwik',

  // Overrides the autogenerated tracker endpoint entirely
  // Default: undefined
  // trackerUrl: 'https://example.com/whatever/endpoint/you/have',

  // Enables automatically registering pageviews on the router
  router: router,

  // Enables link tracking on regular links. Note that this won't
  // work for routing links (ie. internal Vue router links)
  // Default: true
  enableLinkTracking: true,

  // Require consent before sending tracking information to matomo
  // Default: false
  requireConsent: false,

  // Whether to track the initial page view
  // Default: true
  trackInitialView: true,

  // Whether or not to log debug information
  // Default: false
  debug: true
});
```

**Comment by AmazingDreams** [comment]
You mean you used `npm run build` or something similar to build the page for prod?

**Comment by bschulz87** [comment]
vue-cli-service build --modern is used for the build, yes.

**Comment by AmazingDreams** [comment]
Ah great! Would you mind documenting this a little?

**Comment by bschulz87** [comment]
I can create a PR with this approach because it requires a change in  vue-matomo/src/index.js

**Comment by AmazingDreams** [comment]
Sure, then I'll see if I can support it

**Comment by bschulz87** [comment]
That'd be great. It does not work when the script is loaded async, though.

https://gist.github.com/bschulz87/d82661c29c7278a848f54ed6d4ed6705

**Comment by AmazingDreams** [comment]
I see. The problem with async loading is that it breaks `vm.$matomo` stuff which has been causing other kinds of issues:

- https://github.com/AmazingDreams/vue-matomo/issues/3

Then I tried using a proxy that writes to `window._paq` which worked excellent however:

- https://github.com/AmazingDreams/vue-matomo/issues/17

So you see to solve the root of this particular issue can only be solved by creating an entire Vue compatible wrapper around matomo which is just a little too much work for me atm. I'm afraid I can't integrate your solution
