### ISSUE TITLE
Wait for this.$matomo to initialize

### ISSUE THREAD

**Issue by Parnswir** [AmazingDreams/vue-matomo#3]
I'm currently building one of those beloved cookie consent banners with Vue and Matomo (and vue-matomo of course). I want to hide the banner if the user has given their consent (`this.$matomo.hasRememberedConsent() == true`), however, on the first page load `this.$matomo` is undefined (during initialization I suppose). Is there a way to be sure it is loaded before I try to access it?

**Comment by AmazingDreams** [comment]
Ah yes, I had the same issue myself. Unfortunately to really provide you with a truly easy solution I'd have to copy and paste the piwik.js library and have to deal with all those versions etc. Maybe I'll do that anyway but sooner or later it'll be outdated in some way and stuff will break.

I did the following:

```
// in main.js
Vue.use(VueMatomo, {
  host: 'https://matomo.example.com',
  siteId: 5,
  router: router,
  requireConsent: true
})

// in CookieConsent.vue
mounted () {
    const cookieSettings = this.getCookieSettings()

    if (cookieSettings === null) {
      this.show = true
      // Default to essential cookies only
      this.timeoutUntilPiwikSet(['essential'], 0)
    } else {
      this.timeoutUntilPiwikSet(cookieSettings, 0)
    }
},
methods: {
  timeoutUntilPiwikSet (cookieSettings, counter) {
    // People might have a tracking blocker and it won't ever load
    if (counter > 100) {
      console.error('Waiting for $matomo timed out')
      return
    }

    if (this.$matomo) {
      this.handleSelectedSettings(cookieSettings)
    } else {
      setTimeout(() => {
        this.timeoutUntilPiwikSet(cookieSettings, counter + 1)
      }, 10)
    }
  }
}
```

So this should just leave you to implement `getCookieSettings` and `handleSelectedSettings`

**Comment by Parnswir** [comment]
Thank you for your quick answer. I have implemented a timeout-based polling for matomo as well.

On the matter of cookies: By using the matomo API (calling `this.$matomo.rememberConsentGiven()`), it will create a cookie called `mtm_consent`, so I guess you don't need to set your own cookies if you don't do anything fancy with subdomains. :smile:
