### ISSUE TITLE
Wrong record when reloading the page

### ISSUE THREAD

**Issue by eka4ecap** [AmazingDreams/vue-matomo#30]
when the user is on the “localhost/about” page, and the user reloads the page, not the “localhost/about” page that is recorded but page “localhost:8080”
is this default in vue js or not, which is clearly not what I want

**Comment by maderiyan042018** [comment]
i have same issue.
like the plugin start tracking when the plugin initialized

**Comment by AmazingDreams** [comment]
I cannot reproduce this. Can you provide some steps to reproduce?

**Comment by eka4ecap** [comment]
Hi, this is my initialization
![image](https://user-images.githubusercontent.com/47802389/56011616-09b70400-5d1b-11e9-86d3-ee2ebfbd87c5.png)

and this is my code for tracking
![image](https://user-images.githubusercontent.com/47802389/56011295-8fd24b00-5d19-11e9-8c2c-dceedf07d793.png)

this is the record
![image](https://user-images.githubusercontent.com/47802389/56011581-daa09280-5d1a-11e9-833f-bd7713ad1f78.png)

It's normally record if user change page, but wrong record if user reload page. The user is stay on the page register but when the user reloads the page, title that is recorded from index.html
I think it's because of the record from the vue-matomo initialization, and what is read is the title from index.html instead of the title of my tracking code
Can I disable initialization from vue-matomo when the page reloads? or any suggestion to fix this issue?

**Comment by eka4ecap** [comment]
Hi, already resolved
Thanks
