### ISSUE TITLE
Base url not being use for router

### ISSUE THREAD

**Issue by jordan-boyer** [AmazingDreams/vue-matomo#37]
When you set a base url on vue-router, vue-matomo will not take it. 
Example: my full name route is foo/bar/foo and in my router I have a base url set to foo and a route for bar and is children. 
Vue-matomo will only send /bar/foo because it doesn't check on the router option if a base url is set. 

Can easily be fix with : 
`const mayHaveBase = options.router.options && options.router.options.base ? options.router.options.base : ''`
`const url = ${protocol  }//${  loc.host  }${maybeHash  }${mayHaveBase}${to.path}`

**Comment by AmazingDreams** [comment]
Implemented
