### ISSUE TITLE
Url contains // when mode is set to history

### ISSUE THREAD

**Issue by jordan-boyer** [AmazingDreams/vue-matomo#39]
This issues appear after you fix issue #37 

example : When base url is set to bar and route is foo, vue matomo will return `bar//toto`<br>
quick fix: remove last / in `routerBase = /${routerBase}/` and add / before # in `const maybeHash = options.router.mode === 'hash' ? '#' : ''`

**Comment by jhfyang** [comment]
This issue is still ongoing for me with version vue-matomo@3.12.0-5

**Comment by AmazingDreams** [comment]
Will investigate

**Comment by AmazingDreams** [comment]
Should be fixed in v3.13.0-0 thanks to @pdl through #45
