### ISSUE TITLE
error

### ISSUE THREAD

**Issue by echooohce** [AmazingDreams/vue-matomo#4]
Sorry, I‘m coming again.I used your vue-matomo again in my new project. The following error occurred：Uncaught SyntaxError: Unexpected token <   (piwik.js:1 )
vue-matomo.js?d27d:44 Uncaught (in promise) TypeError: Cannot read property 'getTracker' of undefined
    at eval (vue-matomo.js?d27d:44)        (vue-matomo.js?d27d:44).

**Comment by AmazingDreams** [comment]
Is your remote piwik.js loading properly?

**Comment by echooohce** [comment]
Vue.use(VueMatomo, {
    host: "http://matomo.local",
    siteId: 1,
    router: router,
    requireConsent: true
});
Uncaught (in promise) TypeError: matomo.requireConsent is not a function
    at eval (vue-matomo.js?d27d:51)
I use it this way.

**Comment by AmazingDreams** [comment]
What version of matomo are you using? 3.5.1? `requireConsent` was added only a month or two ago

**Comment by echooohce** [comment]
"vue-matomo": "^0.1.8",

**Comment by AmazingDreams** [comment]
I actually meant your matomo server version

**Comment by AmazingDreams** [comment]
Did you manage to get this to work? You can try v0.1.9
