### ISSUE TITLE
this.$matomo is randomly undefined

### ISSUE THREAD

**Issue by halfpastfive** [AmazingDreams/vue-matomo#41]
Hi, 

On version 3.12.0-4, I randomly get a typeError stating `this.$matomo is undefined`

my app is setup as follows : 

main.js : 

```javascript
Vue.use(VueMatomo, {
  host: 'https://stats.my.domain',
  siteId: 2,
  router,
});
```

App.vue : 

```javascript 
this.$matomo.setSiteId(dest.matomoSiteId); // triggers an error
this.$matomo.trackPageView();
```
The triggered error is `TypeError: this.$matomo is undefined`

No issue with the 3.9.1-2 version. 

I noticed that the matomo plugin is loaded asynchronously in the 3.12 version so given the randomness of the error, the script is probably not loaded when I call this.$matomo.

**Comment by AmazingDreams** [comment]
> I noticed that the matomo plugin is loaded asynchronously in the 3.12 version so given the randomness of the error, the script is probably not loaded when I call this.$matomo.

Correct, I've tried to resolve this previously but it is way too much work to resolve it. Using JS proxies causes errors on older browsers, inlining matomo.js is ugly and causes a bunch of other issues, etc

You can use `window._paq.push` though. I'll add a note on it.

```
window._paq.push(['setSiteId', dest.matomoSiteId])
window._paq.push(['trackPageView'])
```

**Comment by AmazingDreams** [comment]
Thanks for reporting, I added a note. Please do not hesitate to reopen if you need any more help.
