### ISSUE TITLE
Parametrize name of 'piwik.js' file and 'piwik.php'

### ISSUE THREAD

**Issue by gelmiro** [AmazingDreams/vue-matomo#53]
Hi,
I have problem with downloading of piwik.js  and 'piwik.php' file. On my server this file have different name (extension to be precise) and plugin fail when try to download it. Could you  give possibility to inject own name (with extension)  for this file for download? For example file on my server have name `foo.bar`

**Comment by gelmiro** [comment]
Ok, I will try to prepare PR

**Comment by AmazingDreams** [comment]
Thanks! I'd suggest looking at the `trackerUrl` option and how it's implemented. Something like `trackerScriptUrl` would be a good name. Maybe 2 LOC and some documentation in README

I'll have some time tomorrow to do the merge and publish a new version

gelmiro <notifications@github.com> schreef op 17 februari 2020 08:04:19 CET:
