### ISSUE TITLE
First page tracked does not take into account the meta information set in the router

### ISSUE THREAD

**Issue by fbonin** [AmazingDreams/vue-matomo#56]
To reproduce : 
1) Set analyticsIgnore in the router on a page
2) Load the URL of the route that has the analyticsIgnore flag on directly (i.e. : http://localhost:8080/page-2)
3) Bug : The URL will be reported to Matomo

**Comment by AmazingDreams** [comment]
Good catch and thanks for the PR, will look into it ASAP

fbonin <notifications@github.com> schreef op 30 maart 2020 00:25:26 CEST:

**Comment by AmazingDreams** [comment]
Thanks!
