### ISSUE TITLE
In my vue project, "action_name" is not change dynamic, so i see the source code and find the problem!

### ISSUE THREAD

**Issue by SeanBurt** [AmazingDreams/vue-matomo#58]
![image](https://user-images.githubusercontent.com/18049638/77892542-58034100-72a5-11ea-9ed8-d2e341f58a60.png)
![image](https://user-images.githubusercontent.com/18049638/77892603-71a48880-72a5-11ea-8a44-4f291e3e6a79.png)

**Comment by AmazingDreams** [comment]
I think this would be a matter of preference, if the title is omitted the URL itself will be used as a title iirc. I personally didn't like the behavior of using a name pulled from the router. I'll play around with some options

Lie <notifications@github.com> schreef op 30 maart 2020 10:43:02 CEST:

**Comment by SeanBurt** [comment]
> I think this would be a matter of preference, if the title is omitted the URL itself will be used as a title iirc. I personally didn't like the behavior of using a name pulled from the router. I'll play around with some options Lie <notifications@github.com> schreef op 30 maart 2020 10:43:02 CEST:
> […](#)
> ![image]([user-images.githubusercontent.com/18049638/77892542-58034100-72a5-11ea-9ed8-d2e341f58a60.png](https://user-images.githubusercontent.com/18049638/77892542-58034100-72a5-11ea-9ed8-d2e341f58a60.png)) ![image]([user-images.githubusercontent.com/18049638/77892603-71a48880-72a5-11ea-8a44-4f291e3e6a79.png](https://user-images.githubusercontent.com/18049638/77892603-71a48880-72a5-11ea-8a44-4f291e3e6a79.png)) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #58

In spa(single page application), title is dynamic when change the router, when you set options once, the action_name is also can't change dynamically, so you must set action_name with router meta in router hook.

**Comment by fbonin** [comment]
I have a PR that uses the title in the router if specified but it is based on the PR on this issue 

https://github.com/AmazingDreams/vue-matomo/issues/56

I can create the PR once approved.

**Comment by SeanBurt** [comment]
> I have a PR that uses the title in the router if specified but it is based on the PR on this issue
> 
> #56
> 
> I can create the PR once approved.

Hi, this pr can't solve my issue, in spa(single page application), title is dynamic when change the router. When you set options once, the action_name is also can't change dynamically, so you must set action_name with router meta in router hook.

**Comment by AmazingDreams** [comment]
Thanks!
