### ISSUE TITLE
Cookie "_pk_id.14.1fff" always created

### ISSUE THREAD

**Issue by ColinSeanKavanagh** [AmazingDreams/vue-matomo#65]
Hello there,

I need an option, where no Cookies are created until consent is given (Opt-In). The option requireConsent is true and trackInitialView is false, however there is always a cookie created called "_pk_id.14.1fff" which contains an id that is trackable. 

Another problem, which seems related: When I want to call the function disableCookies() there seems to be the problem that a "_paq.push(['trackPageView'])" was already called ( see https://matomo.org/faq/general/faq_157/). 

How can I disable the function being called before consent is given?

**Comment by AmazingDreams** [comment]
Hello. There is another configuration option `disableCookies`. I think that you can use it to disable all cookies, and then enable the cookies again when the user has given consent.

**Comment by AmazingDreams** [comment]
It may be worthwhile to take a look at how the options are processed before the matomo script is loaded https://github.com/AmazingDreams/vue-matomo/blob/master/src/index.js#L103

**Comment by adrianwix** [comment]
How can you enable the cookies again? I looked in the Matomo docs and I did not found a method for that

**Comment by AmazingDreams** [comment]
Hmm right I see. It seems that it is not supported to manually enable cookies: https://github.com/matomo-org/matomo/issues/13056

The workaround is to reload the page and then not call disableCookies... I'm afraid I can't do much from this side

**Comment by jordan-boyer** [comment]
I think they a new configuration available [here](https://github.com/matomo-org/developer-documentation/pull/359/files).
We can try to implement this what do you think @AmazingDreams ?

**Comment by AmazingDreams** [comment]
Good find. I think it can be implemented on the application side entirely using the custom pre init actions
