### ISSUE TITLE
Parameter not changing with nuxt ssr mode

### ISSUE THREAD

**Issue by herrpatrickmueller** [AmazingDreams/vue-matomo#69]
when having the plugin in nuxt ssr environment, the parameters in the matomo request are not changing on route change. this seems to be a problem with the lack of meta information in the route. so `title` is `undefined` and parameters do not change.
maybe the `route.path` could be used when no meta information are provided.

**Comment by herrpatrickmueller** [comment]
example:
https://github.com/AmazingDreams/vue-matomo/compare/master...herrpatrickmueller:patch-1

**Comment by AmazingDreams** [comment]
Thank you for the PR. Please let me know if your issue persists
