### ISSUE TITLE
[Question] Update user ID after loading

### ISSUE THREAD

**Issue by sheoak** [AmazingDreams/vue-matomo#73]
The document mention that setUserId must be call before any track* function: https://developer.matomo.org/guides/tracking-javascript-guide

My issue is that I login after matomo has been loaded in my Single Page Application.

How to you update it with vue-matomo then?
The only method I found was to refresh the app, which I would like to avoid.

Thanks!

**Comment by AmazingDreams** [comment]
You can call `setUserId` at any time. So after logging in you can call `this.$matomo.setUserId(userId)` or `_paq.push(['setUserId', 'USER_ID_HERE']);`. The user ID will be included in each tracking request henceforth.

However to ensure that the user ID is included in the initial page view it is best to pass it to the options of `VueMatomo`.

**Comment by jordan-boyer** [comment]
Also, you can initialize matomo only after the user is log in. 
But if you decide to do that, take not that all navigation done before log in will not be track =) 

## Example
```js
await login(user);
Vue.use(matomo, config)
```

**Comment by sheoak** [comment]
> You can call `setUserId` at any time. So after logging in you can call `this.$matomo.setUserId(userId)` or `_paq.push(['setUserId', 'USER_ID_HERE']);`. The user ID will be included in each tracking request henceforth.
> 
> However to ensure that the user ID is included in the initial page view it is best to pass it to the options of `VueMatomo`.

Thank you for your reply and the precision, I thought it would not properly from reading the documention.

**Comment by sheoak** [comment]
@AmazingDreams i realized my issue was that i was guarding my code with `if this.$matomo` in case it's not loaded yet, so sometimes the user id would not be set. Do you have a recommended way to wait for vue-matomo to be loaded? I think it's a very common use case that would be worth documenting? If you have a recommanded way to do it I can implement it and send you a PR with the updated documentation.

**Comment by jordan-boyer** [comment]
@sheoak `_paq.push(['setUserId', 'USER_ID_HERE']);` will be your best option here since this is available even if this.$matomo is not set yet.

**Comment by sheoak** [comment]
> @sheoak `_paq.push(['setUserId', 'USER_ID_HERE']);` will be your best option here since this is available even if this.$matomo is not set yet.

Oh ok, I didn't get that. Thanks!

**Comment by AmazingDreams** [comment]
Yes that is the best way to do it atm. I tried using a proxy once, but it broke compatibility with older browsers.

**Comment by jordan-boyer** [comment]
Proxy is a good idea and i think it can be polyfill.
Until what browsers do you want this repo to be compatible ?

@AmazingDreams Do you want me to create an enhancement issue about this ?

**Comment by AmazingDreams** [comment]
Unfortunately proxies can't be polyfilled https://stackoverflow.com/questions/45285992/es6-proxy-polyfill-for-ie11#45453750

And what browser support is concerned I'd like to support all browsers supported by Vue and Matomo. In this specific case dropping compatability for a slight convenience is not worth it imo. Possibly, we could have an option to enable proxy mode, noting that older browsers won't work
