### ISSUE TITLE
Test / explore Matomo 4 compatibility 

### ISSUE THREAD

**Issue by AmazingDreams** [AmazingDreams/vue-matomo#74]
Matomo 4 has entered beta. Looking at the changelog there are no changes that require much work on our end.

https://developer.matomo.org/changelog#javascript-tracker

**Comment by jordan-boyer** [comment]
What do we do about the `window.Piwik` being deprecated ? 

Should we do this instead `window.Piwik || window.Matomo `

**Comment by AmazingDreams** [comment]
Yeah that's probably the best thing to do, however I think it's better to swap them around to make sure that Matomo is preferred over Piwik

**Comment by jordan-boyer** [comment]
Yeah i think you're right about this one

**Comment by sbillet** [comment]
Hello @AmazingDreams, thanks for your work on the Vue integration 👍 

Matomo 4 was officially released in November.
Is vue-matomo compatible? Could you add a hint to the readme?
If it is not compatible, when do you plan to release a compatible version?

**Comment by AmazingDreams** [comment]
@sbillet I have been running Matomo 4 for quite a while now and encountered no issues so far
