### ISSUE TITLE
Vue 3/Vite compatibility

### ISSUE THREAD

**Issue by schuch** [AmazingDreams/vue-matomo#75]
When trying to use `vue-matomo` (v3.14.0-0) with Vue 3/Vite the following error occurs:

```
[Vue warn]: A plugin must either be a function or an object with an "install" function.
```

My `main.js`

```javascript
import matomo from 'vue-matomo'
import { createApp } from 'vue'
import App from './App.vue'
import './index.css'

createApp(App)
  .use(matomo, {
    host: 'https://matomo.example.com',
    siteId: 42,
  })
  .mount('#app')
```

It works when importing `src`:
```javascript
import matomo from 'vue-matomo/src'
```
which explains, why the example for vue3 in this repository worked.

Steps to reproduce:
```
$ npm init vite-app vue3-matomo-demo
$ cd vue3-matomo-demo
$ npm install --save vue-matomo
```
edit `main.js` according to the example above

```
$ npm install
$ npm run dev
```
Open http://localhost:3000 and check the console

**Comment by jordan-boyer** [comment]
I do not have experience with Vite but i'll check it out.

**Comment by jordan-boyer** [comment]
Base on [this](url) I think it's intended since it's only support natif ES import.

And it's mainly because we are using a default export for the install function. 

Another syntax you can use is 
```js
import matomo from 'vue-matomo'
import { createApp } from 'vue'
import App from './App.vue'
import './index.css'

createApp(App)
  .use(matomo.default, {
    host: 'https://matomo.example.com',
    siteId: 42,
  })
  .mount('#app')
```

**Comment by schuch** [comment]
Thanks ❤️ , using `matomo.default` works.

The link you mentioned does not point to anything.

**Comment by AmazingDreams** [comment]
Seems like something with the type of packager used?

**Comment by jordan-boyer** [comment]
@schuch sorry about the link it's fix now.

@AmazingDreams I was thinking the same thing.

**Comment by jordan-boyer** [comment]
I'm working on a patch for this, but for now it's working for vue 2 and 3 with webpack but not for vite. 

I'll try to make it work by the end of the week.

**Comment by schuch** [comment]
Since vite 1.0.0-rc5 the workaround of using `matomo.default` stopped working for us. Instead the documented way of usage is working now 🎉 

I think something about how rollup.js is used has changed. May be related to https://github.com/vitejs/vite/pull/746.

**Comment by jordan-boyer** [comment]
Thx letting us know =)
