### ISSUE TITLE
Automated tracking

### ISSUE THREAD

**Issue by marcohajek** [AmazingDreams/vue-matomo#76]
Is it possible to disable any automated tracking done by vue-matomo?

We have multiple vue components where we only want to track some button clicks. But even with trackInitialView: false vue-matomo sends a request when the page gets loaded. Is there a way to disable this behavior?

**Comment by jordan-boyer** [comment]
Can you tell me what kind of request is made ?

**Comment by marcohajek** [comment]
A get request with the given trackingUrl and as action_name the the content of the title node of the html file.

**Comment by jordan-boyer** [comment]
If it's a get it's normal, this do not track the user but only download the resources to do so eventually.

**Comment by AmazingDreams** [comment]
I think you can use this config:

```
  router: undefined, // Or simply omit, disables navigation event tracking
  enableLinkTracking: false,
  trackInitialView: false, // You stated you are already doing this
```

If possible can you provide the config you are using?

**Comment by marcohajek** [comment]
I am currently using this config:
`{
        host: '',
        siteId: 36,
        trackerFileName: 'piwik',
        trackerUrl: '',
        enableLinkTracking: false,
        router: undefined,
        trackInitialView: false,
        debug: true,
        preInitActions: []
    }`

I don't think this request is "normal" because it shows as action on the matomo webinterface. And we only want it to show on the webinterface, when someone presses a button and not when navigating to that page.

**Comment by AmazingDreams** [comment]
Hmm weird, I'll see if I can set up a reproduction

**Comment by marcohajek** [comment]
Hey again,
I just wanted to let you know, that we found our issue and it was as expected not on your end.
In the one component where the initial trackPageView request got sent was still an old js file included. This one hat an own instance of matomo declared and did the trackPageView manually. We've removed the import and now everything works fine.

Sorry for wasting your time.

**Comment by AmazingDreams** [comment]
Ah cool, don't worry about it. I hadn't really gotten around to more than a quick change of the options, so it's fine. Thanks for getting back!
