### ISSUE TITLE
The average page generation time is incorrect

### ISSUE THREAD

**Issue by gaoyaowang** [AmazingDreams/vue-matomo#77]
![1](https://user-images.githubusercontent.com/38639693/98344407-2974f200-204e-11eb-9039-6b7841b67246.png)

My page generation time is 30 to 50 milliseconds, which is not in line with the actual situation!

My approach is:
![2](https://user-images.githubusercontent.com/38639693/98344730-a2744980-204e-11eb-98d9-b066499fd278.png)
Because my routing parameters are too long, I can't use router: router,

So I do this in components
![3](https://user-images.githubusercontent.com/38639693/98346193-96898700-2050-11eb-8704-2b63a6bc06eb.png)

What's wrong with what I wrote? What kind of configuration is missing
Sorry, my English is not very good. I hope you can understand my problem

**Comment by AmazingDreams** [comment]
Hello, your English is fine! You may be interested in the Matomo docs on SPA, specifically on setting the page generation time https://developer.matomo.org/guides/spa-tracking#updating-the-generation-time

**Comment by gaoyaowang** [comment]
Sorry, I couldn't get back to you in time, I've tried this,
this.$matomo.setGenerationTimeMs(loadTime);
I use window.performance.timing To get the load time,But Vue is a single page application,Route switching, using window.performance.timing The correct load time cannot be obtained.Do you have any good suggestions or methods?

**Comment by AmazingDreams** [comment]
Not really. I think your best option is to set the current time in a component mounted method, then after the component is done loading async data calculate the loading time. However this means you have to manually register page views etc. I think it's possible to create some utility methods in vue-matomo to aid with this setup, but I can't see a way to do this within this library entirely as we don't know what your app is doing.

**Comment by gaoyaowang** [comment]
My app is using Vue matomo to count all kinds of main indicators to achieve the purpose of data analysis. However, as I said earlier, the problem I am facing now is that the page loading time of matomo statistics is incorrect. At present, I can only set it manually.

Thank you for providing me with some directions. Thank you very much!
