### ISSUE TITLE
What are the breaking changes of 4.0?

### ISSUE THREAD

**Issue by slaweet** [AmazingDreams/vue-matomo#90]
## What is the current situation?

I'm trying to stay up-to-date with the latest versions of all dependencies. There are tools like https://renovatebot.com/ that will open PRs for me that include release notes. 
![Screenshot from 2021-05-10 08-56-43](https://user-images.githubusercontent.com/1254342/117618092-be77b580-b16d-11eb-83ec-58f387c98fa7.png)

It's quite hard to asses if the dependency is safe to upgrade or there are some breaking changes. In this case, I had to go through https://github.com/AmazingDreams/vue-matomo/compare/v3.13.5-0...v4.0.0 to see what the changes are. I think there are no breaking changes, but still not highly confident about it. If every developer upgrading vue-matomo has to do this and each takes just 0-15 minutes to go through the changes (depending on how confident they want/need to be), it's a lot of time when summed together.

## What could it be like?

I would very much appreciate it if a major release contained a description of what the breaking changes are. 

As an example of what it could look like, see https://github.com/okonet/lint-staged/releases/v11.0.0 

Then the PR from renovate bot looks like this:
![Screenshot from 2021-05-10 08-56-19](https://user-images.githubusercontent.com/1254342/117618122-c899b400-b16d-11eb-95ef-0dc217e2ea9a.png)

**Comment by AmazingDreams** [comment]
You are right. There are no breaking chances. For historical reasons, I was following the release version of matomo. However this is not necessary anymore, and I planned to adhere to semver after a 4.x release

You can safely upgrade, I will include a changelog

**Comment by AmazingDreams** [comment]
I have created a changelog through the github release feature. If possible I'd be interested to see how this turns out with renovate bot. Let me know if you have any more issues.

**Comment by slaweet** [comment]
> I have created a changelog through the github release feature. If possible I'd be interested to see how this turns out with renovate bot. Let me know if you have any more issues.

Thank you @AmazingDreams. I think it would work well with renovate bot.

I can't check and show you, because I merged the PR from renovate bot after your first comment that confirmed there are no breaking changes, so it won't update the PR description with your changes of the release notes.
