### ISSUE TITLE
No changes after config editing

### ISSUE THREAD

**Issue by bynifaciy** [AmazingDreams/vue-matomo#94]
After set  "enableHeartBeatTimer" to true and "heartBeatTimerInterval" to 1 in matomo.ts i still see in matomo visits with 0s duration time

Any ideas?

**Comment by AmazingDreams** [comment]
Do you see heartbeat pings in the network tab?

**Comment by ezawadzki** [comment]
Hi @AmazingDreams, Same issue and I don't see heartbeat pings in the network tab. Any idea ?

**Comment by AmazingDreams** [comment]
Hello @ezawadzki. I have just tried to reproduce this. I got it to work more reliable when using a heartbeat timer interval of at least 5 seconds. According to https://forum.matomo.org/t/0s-pageviews-even-though-heartbeat-time-is-enabled/38161/7 the minimum heartbeat is 5 and any value lower than that resets it to 5. But when i used 1 in debugging, it only sent 1 request, and basically no more after.

**Comment by ezawadzki** [comment]
Hi @AmazingDreams, thanks for your answer. I setted `heartBeatTimerInterval` at 5 as in the example. Tried to 15 sec, not working too. I connected my site to a friend instance of Matomo (4.4.1), same behaviour.
Here some details of the behaviour after multiple test :
The site request matomo with this kind of request `.../piwik.php?ping=1&...` after 2-3min being on the same page. Sometimes a second request appear 2min later... Sometimes not. Very random. If I set "heartBeatTimerInterval" at 5, it should ping every 5sec ? Am I right ?

Tested on a fresh install hello world vuejs SPA project :
Matomo: 4.4.1 and 4.8.0
vue: "^3.2.31",
vue-matomo: "^4.1.0",
vue-router: "^4.0.14"
node: 12 and 16.10.0
Browser: Chrome / Brave

Here is the har file (please delete .txt extension) : [example_chrome.har.txt](https://github.com/AmazingDreams/vue-matomo/files/8418314/example_chrome.har.txt)
