### ISSUE TITLE
Setting custom document title

### ISSUE THREAD

**Issue by ristemingov** [AmazingDreams/vue-matomo#99]
Hi,

Matomo documentation has example of custom setting document titles 

https://developer.matomo.org/guides/tracking-javascript-guide#javascript-tracker-features 

especially this example:

`_paq.push(['setDocumentTitle', document.domain + "/" + document.title]);`

Can this be achieved here?

Thanks.

**Comment by jordan-boyer** [comment]
We don't have a direct option for this but as writting in the doc you have acces to _paq in the window. 

So you can just write :
```
if (window._paq) {
   window._paq.push(['setDocumentTitle', document.domain + "/" + document.title]);
}
```

**Comment by AmazingDreams** [comment]
Also

```
this.$matomo.setDocumentTitle(document.domain + "/" + document.title)
```
